

on:
  push:
    branches: [main]
jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [pink, brown]
        include:
          - shape: round
            pet: cat
          - behavi: block
    steps:
      - run: echo "Hello ${{ matrix.color }} ${{ matrix.pet }}"
