name: Outcome vs Conclusion Demo

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate failure
        timeout-minutes: 5
        id: build_kev1
        run: exit 1
      #  continue-on-error: true  # This allows the job to continue even if this step fails

      - name: Check outcome
        id: build_kev2
        if: steps.build_kev1.outcome == 'failure'
        run: | 
          echo "step build_kev1 outcome ${{ steps.build_kev1.outcome }} "
          echo "step build_kev1 conclusion ${{ steps.build_kev1.conclusion }} "
  test:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # This job runs regardless of build outcome
    steps:
      - name: Run tests
        run: echo "Running tests..."

  notify:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: needs.build.steps.build_kev2.conclusion == 'failure' || needs.test.conclusion == 'failure'
    steps:
      - name: Notify failure
        run: echo "One of the jobs failed (based on conclusion)."
