name: Python Shell Example

on: 
  workflow_dispatch :

jobs:
  run-python-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Run inline Python code
        run: |
          print("Hello from GitHub Actions using shell: python!")
          import platform
          print("Python version:", platform.python_version())
        shell: python
