name: Branch Filter with startsWith_freature()

on:
  push:
    branches:
      - '**'

jobs:
  check-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print branch name
        run: 'echo "Branch: ${{ github.ref }}"'

      - name: Run only on feature branches
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: echo "This is a feature branch!"

      - name: Set output using workflow command
        run: echo "branch=feature-branch" >> $GITHUB_OUTPUT
        id: set-output

      - name: Use error
        id: error-use
        run: echo "::error::some error happened"
     
      - name: Use exit
        id: use-exit
        run: exit 1
        
      - name: Use output
        if: ${{ failure() }} || steps.error-use.outcome == "success"
        run: |
          echo "The branch is ${{ steps.set-output.outputs.branch }}"
          echo "The previous step outcome is ${{ steps.use-exit.outcome }}"
          echo "The previous step conclusion is ${{ steps.use-exit.conclusion }}"
