name: Comment when opened using github cli
on:
  pull_request:
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment 13 $PULL_REQUEST_NUMBER --body "Hi commment pr " 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULL_REQUEST.LINK: ${{ github.event.pull_request._links }}
