name: variables - test

on:
  workflow_dispatch:

defaults: 
  run: 
    shell: bash

jobs:

  job1: 
    # environment: prod
    runs-on: ubuntu-latest
    env:
      VAR1: "hello"
    
    steps:
    - run: echo "VAR2=$VAR1" >> $GITHUB_ENV 
    - run: echo "VAR3=KEVIN" >> "$GITHUB_ENV"
    - run: echo $VAR2 $VAR3
    - name: Show contents of $GITHUB_ENV
      run: cat $GITHUB_ENV
    - name: Show contents of $GITHUB_ENV using env 
      run: env 
    - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
    - run: exit 1
      name: exit
    - run: exit 0
      name: exit2
      continue-on-error: true

