on: push
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          # echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TEST: ${{ github.action_path}}
        run: |
           # # echo "$GITHUB_CONTEXT"
           #  echo "${{ github.action_path }}"
           # # echo "GITHUB.ACTION_PATH"
           # # echo $GITHUB_TEST
           ls ${GITHUB_ACTION_PATH}/workflows
           echo " pwd "
           pwd
           echo " ls"
           ls
