name: variables - test

on:
  workflow_dispatch:
  
jobs:
  job1: 
    runs-on: ubuntu-latest
    env:
      VAR1: "hello"
    
    steps:
    - run: echo "VAR2=$VAR1" >> $GITHUB_ENV 
    - run: echo $VAR2
    - name: Show contents of $GITHUB_ENV
      run: cat $GITHUB_ENV
    - name: Show contents of $GITHUB_ENV using env 
      run: env 
    - run: cat $GITHUB_EVENT_PATH
    - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
       

